sudo: required

language: go
go:
  - "1.14"

go_import_path: github.com/fmitra/authenticator

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    - stage: test
      script:
        - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0
        - make dev
        - docker-compose up -d
        - make test
        - make lint
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      if: tag =~ ^v
      script:
        - export REPO=fmitra/authenticator
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build . -f Dockerfile -t $REPO
        - docker tag $REPO $REPO:$TRAVIS_TAG
        - docker push $REPO
