sudo: required

language: go
go:
  - "1.11"

go_import_path: github.com/fmitra/authenticator

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    - stage: test
      script:
        - docker-compose up -d
        - make lint
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      if: tag =~ ^v
      script:
        - export REPO=fmitra/authenticator
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build . -f Dockerfile -t $REPO
        - docker tag $REPO $REPO:$TRAVIS_TAG
        - docker push $REPO
