version: '3'

networks:
  authenticator:
    driver: bridge

services:
  postgres:
    restart: unless-stopped
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=swordfish
      - POSTGRES_DB=authenticator_test
    networks:
      - authenticator

  redis:
    restart: unless-stopped
    image: redis:5.0.4
    ports:
      - 6379:6379
    command: redis-server --requirepass swordfish
    networks:
      - authenticator
