version: '3'

networks:
  authenticator:
    driver: bridge

services:
  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=swordfish
      - POSTGRES_DB=authenticator_test
    networks:
      - authenticator

  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379
    command: redis-server --requirepass swordfish
    networks:
      - authenticator

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - authenticator

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost

      # Broker uses to create sockets. These are the interfaces
      # kafka binds to.
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      # Advertised listeners are how clients connect
      # When client connects to broker, broker will retireve
      # information from zookeeper and tell the client its available at
      # this location. `kafka:9092` is fine inside a docker network
      # as `kafka` is resolve, outside your client has no way of
      # knowing where this is.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # <topic name>:<partition>:<replicas>
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - authenticator
