name: Build

on:
  push:
    branches:
    - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        docker-compose -f docker-compose.test.yml up -d
        make dev
        go get -v ./...
    - name: Test
      run: make test
    - name: Codecov upload
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
